<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * ChatMessage — A single message in a doctor's AI copilot conversation.
 *
 * The `sender` field distinguishes between messages sent by the doctor
 * and responses generated by the AI assistant.
 *
 * @property int    $id
 * @property int    $conversation_id
 * @property string $sender   'doctor' | 'ai'
 * @property string $content
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 */
class ChatMessage extends Model
{
    use HasFactory;

    protected $fillable = [
        'conversation_id',
        'sender',
        'content',
    ];

    // ─── Relationships ────────────────────────────────────────────

    public function conversation(): BelongsTo
    {
        return $this->belongsTo(ChatConversation::class, 'conversation_id');
    }

    // ─── Helpers ─────────────────────────────────────────────────

    public function isFromDoctor(): bool
    {
        return $this->sender === 'doctor';
    }

    public function isFromAi(): bool
    {
        return $this->sender === 'ai';
    }
}
